// THIS FILE IS GENERATED BY FlutterFire CLI.
// Run: flutterfire configure
// After adding your google-services.json to android/app/
//
// DO NOT edit this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS not configured.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  // ----------------------------------------------------------------
  // REPLACE all values below with those from your Firebase Console.
  // Go to: Project Settings → Your apps → Android → google-services.json

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkrIWRilmLcgRo7teQ46tcnB523S5dYLQ',
    appId: '1:347863575058:android:2d023b6867c5269e7dc6cb',
    messagingSenderId: '347863575058',
    projectId: 'agri-doctor-ea09c',
    storageBucket: 'agri-doctor-ea09c.firebasestorage.app',
  );

  // ----------------------------------------------------------------
}